### ISSUE TITLE
djrill admin throws `ImproperlyConfigured` on Django 1.8.6

### ISSUE THREAD

**Issue by rotherfuchs** [brack3t/Djrill#104]
On https://djrill.readthedocs.org/en/v1.4/installation/#admin-optional it's mentioned to add `django.contrib.admin.apps.SimpleAdminConfig` to the `INSTALLED_APPS` when on 1.7+. However, doing so throws `django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: admin` .

I don't know if this works on Django 1.7, though.

**Comment by medmunds** [comment]
Do you maybe have both `'django.contrib.admin'` and `'django.contrib.admin.apps.SimpleAdminConfig'` in your `INSTALLED_APPS`? You need to remove the first one when adding the second one.

(If that's not the problem, it would help to see at least the INSTALLED_APPS portion of your settings.py, along with the section of your urls.py where you're setting up admin.)

Also, please note that the Djrill admin is very much optional, and really doesn't provide any functionality that's not already available in Mandrill's own dashboard. Unless there's some reason you really want the Djrill admin, it's probably easier to just skip it altogether.

**Comment by rotherfuchs** [comment]
Got it, didn't see the comment "instead of '`django.contrib.admin`' . However, the admin now works but shows me "You do not have permission to change anything", though I'm logged in with a superuser account and it works perfectly w/o the `django.contrib.admin.apps.SimpleAdminConfig`.

I do understand this is optional - but it would be of much convenience to have that information in the application directly.

Thanks for your help!

**Comment by medmunds** [comment]
Are you calling `admin.autodiscover()` in your urls.py? You'll need to with SimpleAdminConfig.

**Comment by medmunds** [comment]
Assuming you got this working; let us know if not.
