### ISSUE TITLE
Key Error 'event'

### ISSUE THREAD

**Issue by andrewfam** [brack3t/Djrill#108]
```
@receiver(webhook_event)
def handle_all(sender, event_type, data, **kwargs):
	print "Testing HEAD"
	if event_type == 'inbound':
		cdata = data['msg']['to'][0][0].split('@')[0].split('~')
		cuuid = cdata[0]
		hotel_id = cdata[1]		
		client = Client.objects.get(uuid=cuuid)
		connection.set_tenant(client)
		try:
			attachments = data['msg']['attachments']
			akeys = attachments.keys()
			for k in akeys:
				data = attachments[k]['content']
				
				ie = InEmail.objects.create(odata=data)
				import_data_to_models.delay(client.id, hotel_id, ie.id)
		except:
			pass	
	else:
		try:
			metadata = data['msg']['metadata']
			client = Client.objects.get(uuid=metadata['client'])
			connection.set_tenant(client)
			oe = OutEmail.objects.get(uuid=metadata['oe'])
			oe.data = data 
			oe.oe_type = event_type
			oe.save()
			print "Testing Done"
		except:
			pass
```

I'm getting a key error Event occasionally.

    ```
return view_func(*args, **kwargs)
  File "/Users/andrewfam/.virtualenvs/snagfin/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/andrewfam/.virtualenvs/snagfin/lib/python2.7/site-packages/djrill/views.py", line 67, in dispatch
    request, *args, **kwargs)
  File "/Users/andrewfam/.virtualenvs/snagfin/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/andrewfam/.virtualenvs/snagfin/lib/python2.7/site-packages/djrill/views.py", line 82, in post
    sender=None, event_type=event['event'], data=event)
KeyError: 'event'



```

**Comment by medmunds** [comment]
It looks like this could occur if your Mandrill webhook is configured to send whitelist/blacklist sync events. 

The [sync events](https://mandrill.zendesk.com/hc/en-us/articles/205583297-Sync-Event-Webhook-format) webhook didn't exist when webhook support was added to Djrill, and it seems to not follow the format of the earlier [message](https://mandrill.zendesk.com/hc/en-us/articles/205583307-Message-Event-Webhook-format) and [inbound](https://mandrill.zendesk.com/hc/en-us/articles/205583207-What-is-the-format-of-inbound-email-webhooks-) event webhooks that both use an `'event'` key to identify their types.

We'll need to update Djrill to handle sync events. In the meantime, a workaround is to un-check the "Rejection Whitelist Changes" and "Rejection Blacklist Changes" triggers for the Djrill webhook in your Mandrill webhooks config: https://mandrillapp.com/settings/webhooks. (There's an "edit" command for an existing webhook hiding in the arrow next to "send test".)

(If you *don't* have the rejection blacklist/whitelist triggers set, then there's some other problem with Mandrill sending out-of-spec data. If that's the case, it would be helpful to see the `event` object from the line that's failing.)

**Comment by andrewfam** [comment]
Thanks for this i'll check it out
