### ISSUE TITLE
Future of Djrill (an open letter to Djrill users)

### ISSUE THREAD

**Issue by medmunds** [brack3t/Djrill#111]
> **tl;dr**
> - **If you are switching ESPs** and liked Djrill, take a look at [django-anymail](https://github.com/anymail/django-anymail).
> - **Djrill is seeking a new maintainer.** If none emerges in a few weeks, Djrill will transition to "mature" status. It will receive security updates, but no other maintenance.

For a little over three years, it's been my pleasure to act as Djrill's primary maintainer. However, I won't be continuing in that role. My company is switching to another ESP, and I'll no longer have access to the Mandrill APIs for Djrill development and testing.
#### If you're a Djrill user switching to another ESP...

Please consider joining us over at [django-anymail](https://github.com/anymail/django-anymail). Anymail is a Djrill fork that supports Mailgun, Postmark, SendGrid, and (perhaps) other feature-rich transactional ESPs. 

Anymail's goal is helping you use those rich ESP features in Pythonic, Djangotic code (like Djrill did), while trying to minimize the pain of switching ESPs. It's meant to be an easy migration from Djrill (at least for your Django code). Testers and contributors welcome!
#### If you're staying with Mandrill...

... and would be interested in taking over maintenance of Djrill, please get in touch. (My email's in my GitHub profile.)

If no new maintainer emerges in the next few weeks, I'll transition Djrill to "Development Status :: 6 - Mature" in PyPI. It should continue working, unless/until Mandrill retires the API it uses. If any security updates are needed (there's only been one in Djrill's history), I'll do my best to release them. But I can't realistically support new features or even handle maintenance without access to Mandrill's API.

(Incidentally, since some may ask: I did reach out to Mandrill and offer to continue maintaining Djrill, if they'd be able to provide a test API key. Their response was that "testing or developing integrated services" like Djrill doesn't fit with their pivoting business model.)
#### Either way, thanks!

I've appreciated the participation and support of Djrill's users, and the fixes and truly constructive additions from its contributors over the past three years. Thank you for being part of Djrill. 

And a special thanks to Kenneth Love and Chris Jones from brack3t, the original authors of Djrill, who have been nothing but supportive of my role as a maintainer. 

Lastly, I'd like to tip my hat to the folks behind Mandrill. While we probably all wish MailChimp had allowed for a more graceful transition period, I can understand their business decision. And I think we've all benefited from Mandrill's influence on the transactional ESP market. Mandrill's [introduction](https://web.archive.org/web/20120501184807/http://mandrill.com/) (back in May, 2012) brought us _highly feature rich,_ rock solid, developer friendly transactional email, _much_ more affordably than most full-featured transactional ESPs at the time. I have tremendous respect for the Mandrill team's "startup within a large company" [experiment](https://web.archive.org/web/20121013205348/http://blog.mandrill.com/starting-is-hard-to-do.html), and the nearly four years of value my own startup got from it.

Cheers,
Mike

**Comment by anderspetersson** [comment]
Thanks for you work! I just switched to django-anymail and Mailgun.

**Comment by gavinwahl** [comment]
It looks like django-anymail supports mandrill too. Is there any reason to use Djrill for new code? (I only need mandrill support)

**Comment by medmunds** [comment]
@gavinwahl django-anymail would _probably_ be preferred for new code, ~though hasn't caught up yet to some of Djrill's features (delivery webhooks, inbound email handling, Mandrill templates)~
 [edit: Anymail has all of these now, as of v1.3]. And since anymail is focused on common transactional email features, it may never implement all of the detailed Mandrill options that Djrill offers.

However, both anymail and Djrill suffer from the same problem going forward: there's no way for us to test the packages against Mandrill's APIs (without paying $480/year). There's always a risk of developing to API docs without being able to access the actual API for testing and debugging.

If you're confident your project will be staying with Mandrill, another option would be Mandrill's own python API bindings. Although they don't have Django-specific integration like Djrill, presumably MailChimp will be maintaining them and offering support to their customers.

**Comment by medmunds** [comment]
There being no takers for the position of "Djrill maintainer", I'm releasing the (likely) final version of Djrill and marking the project "inactive". (If you're finding this discussion years from now and interested in resurrecting Djrill, feel free to get in touch.)

Otherwise, see you all at [Anymail](https://github.com/anymail/django-anymail).
