### ISSUE TITLE
Make available message ID

### ISSUE THREAD

**Issue by NadyaIonova** [brack3t/Djrill#114]
Mandrill api returns message ID in response. Make it available for caller. 

Suggested solution: customizable callback hook.

**Comment by NadyaIonova** [comment]
I can create PR for this, if it's a good idea.

**Comment by medmunds** [comment]
Mandrill's message ID is available in the `mandrill_response` that Djrill adds to the EmailMessage as it's sent. See [response from Mandrill](https://djrill.readthedocs.io/en/latest/usage/sending_mail/#response-from-mandrill) in the docs.

[Also, wanted to make sure you know that the Djrill package is no longer being maintained. See the notice at the top of the [readme](https://github.com/brack3t/Djrill/blob/master/README.rst).]

**Comment by NadyaIonova** [comment]
I see, thanks for answer.
