### ISSUE TITLE
Support sending non-binary attachments

### ISSUE THREAD

**Issue by terite** [brack3t/Djrill#68]
The mandrill api for attachments has a `binary` boolean for if the data is binary or not. I would like to set this to `false` so my `text/calendar` attachment is human readable in the email source.

I do not see support for setting this option for an attachment.

https://mandrillapp.com/api/docs/messages.python.html#method=send

**Comment by medmunds** [comment]
As far as I can tell, Mandrill's `binary` attachment flag is a *return value* from their
[parse API](https://mandrillapp.com/api/docs/messages.JSON.html#method=parse).

It doesn't look like the [send API](https://mandrillapp.com/api/docs/messages.JSON.html#method=send) supports *setting* binary for sending attachments. The send documentation says that the attachment content must be provided "as a base64-encoded string".

It sounds like a good feature request for Mandrill, and if they added it, we could support it in Djrill.
