### ISSUE TITLE
2.x: drop support for DjrillAdminSite

### ISSUE THREAD

**Issue by medmunds** [brack3t/Djrill#78]
Proposal for v2.x: remove the custom DjrillAdminSite.

I'd be curious to hear how often people are actually using the Djrill admin views from within their Django projects' admin sites. (And which admin features you're using.) Please add comments to this issue if you have strong feelings one way or the other.

Rationale for removing this functionality:

* At this point, DjrillAdminSite mainly duplicates reporting functionality that's available (in more useful form) in Mandrill's own control panel.
* The admin views add significantly to the Django version compatibility burden. (E.g., Djrill needs to register its own cycle templatetag for compatibility, purely because of the admin templates.)
* I suspect most Djrill users never look at the Djrill admin views. (Thus the request for feedback above.)

(Incidentally, the admin views originally helped site owners add and validate Mandrill senders -- a process that was relatively cumbersome at the time. But Mandrill dropped that requirement years ago, and we removed it from Djrill as well.)

**Comment by kevgathuku** [comment]
I am strongly for removing it. I believe it's causing more trouble than benefit.
I am experiencing a somewhat similar issue to what @walgitrus is experiencing.
The issue is that the Djrill admin simply does not work with the Grapelli admin interface.
Changing the settings as suggested in #74 breaks the Grapelli admin and takes me back to Django's default theme.

**Comment by medmunds** [comment]
@kevgathuku if you're willing to run dev code, DjrillAdminSite is already gone from the v2.0-dev branch. You could install from there. (Dev is, of course, not released. But the tests are passing. I'm going to try to push 2.0 forward to beta my next free weekend.)
