### ISSUE TITLE
Document how to display inline images in multipart/html

### ISSUE THREAD

**Issue by andybak** [brack3t/Djrill#86]
Is it as simple as having markup such as:

    <img src="cid:img1.png">

**Comment by andybak** [comment]
(PS - I'm aware I could just try it myself but I added this issue more as a reminder as I won't be back working on this for a week or so)

**Comment by medmunds** [comment]
I think it's some combination of using the cid in your html part as you've shown, and then making sure your image attachment gets that same cid. (But definitely outside my area of expertise.)

A few comments:
* It would be great to have this documented. If you get it figured out, pull request very welcome.
  (Or even "here's what I did that worked," and I can add it to the docs if you prefer.)
* Most of this is probably not Djrill/Mandrill specific, so other references to using inline images
  with Django EmailMessage/EmailMultiAlternatives would likely apply.
* I'm under the impression that support for displaying inline images is _highly_ email client
  dependent, and comes with all sorts of caveats and exceptions. (Like so much of html email.)
  So your testing needs to consider whether your email client even allows it.
  MailChimp, Litmus, and EmailOnAcid all often publish useful info about email client behavior.

**Comment by medmunds** [comment]
The successor to Djrill, [Anymail](https://github.com/anymail/django-anymail), has first-class support for inline images, including [documentation](http://anymail.readthedocs.org/en/latest/sending/anymail_additions/#inline-images)
