### ISSUE TITLE
Nested merge vars

### ISSUE THREAD

**Issue by nikolaz111** [brack3t/Djrill#88]
Is there a way to send a complex object through merge vars? Mandrill supports any json object to be sent through merge vars. It would be veeeeeeery nice to be able to send something like a ```list``` that has many ```dicts``` which also have ```lists```, etc.

**Comment by medmunds** [comment]
Djrill uses Python's standard [json package](https://docs.python.org/3.4/library/json.html) to encode the Mandrill API calls, so dict and list merge vars should get converted to json in the usual ways.

What happens when you try it?

**Comment by nikolaz111** [comment]
The problem was that one of my nested objects wasn't a standard python dict. It was a different kind of dict, so I had to convert the object to json first and then re parse the info so that everything was json serializable. It works. Thanks

**Comment by nikolaz111** [comment]
By the way, I had to use a custom encoder for json transformation.
