### ISSUE TITLE
Unsubscribe Tag

### ISSUE THREAD

**Issue by aronysidoro** [brack3t/Djrill#90]
Is there an easy way to add the default Mandrill Unsubscribe link?  

Or the best way to do this is through a webhook or custom link to one's own site to manage unsubscribes?

Thanks

**Comment by medmunds** [comment]
You can add a Mandrill unsubscribe link through with an [UNSUB merge tag](http://help.mandrill.com/entries/23815367) (which only works inside Mandrill/Mailchimp templates), or through an automatic unsubscribe footer (which is a Mandrill account setting). Here's lots of [info about unsubscribing in Mandrill](http://help.mandrill.com/entries/21813787). Mandrill also adds a List-Unsubscribe header to every message, which gets used by the Unsubscribe features in several webmail clients.

However, the Mandrill unsubscribe link might not actually do what you want. It adds the email to your Mandrill rejection blacklist, and as they point out:

> The rejection is temporary, and in many cases it doesn't make sense for people to unsubscribe from transactional emails.

So your idea to use a custom link to your own site might work better. For example, I use django-mailer on one of my sites, and have a custom unsubscribe link that adds the address to django-mailer's do-not-send list (which is permanent, unlike Mandrill's blacklist). But we effectively ignore that do-not-send list for certain transactional emails like password resets.

You could also use a [Djrill webhook](https://djrill.readthedocs.org/en/stable/usage/webhooks/) to catch unsubscribe events from Mandrill (e.g., when people unsubscribe through the List-Unsubscribe header), and use that to maintain your own do-not-send list in your app.

Mandrill support might be able to provide more details on the UNSUB merge tag and other Mandrill-side options. You'd have to contact them directly or on StackOverflow -- I don't think they monitor the Djrill project.

**Comment by aronysidoro** [comment]
@medmunds thank you for providing such a thorough explanation of the different options.  That helps a lot, and I think that I have (and other future readers of this) will have a good idea of how to correctly manage the unsubscribes with Djrill.

Thanks!
