### ISSUE TITLE
How to use handlebars loops with Djrill

### ISSUE THREAD

**Issue by kevgathuku** [brack3t/Djrill#92]
Hi,
I am having some trouble with inserting some dynamic content in my templates.
I am trying to pass multiple objects to the template in order to use the for loops feature in Mandrill templates. I followed the [examples](http://blog.mandrill.com/handlebars-for-templates-and-dynamic-content.html#examples) and I am not able to pass multiple elements in the merge vars.
This is my attempt so far:
```
msg.merge_vars = {'users': []}
for user in user_list:
            msg.merge_vars['users'].append(
                {
                    'name': user.first_name,
                    'role': user.role,
                    'id': user.id
                })
```
The corresponding template has a handlebars for loop that iterates over the users and displays the info.

What would be the best way to implement passing multiple elements to the template under a single key?
Thanks in advance.

**Comment by medmunds** [comment]
I think you might be mixing up Mandrill's `global_merge_vars` and `merge_vars`. You probably want *global*_merge_vars for what you've written. But if you do want to use merge_vars, those need to be set *per-recipient*. See [the example in the Djrill docs](https://djrill.readthedocs.org/en/latest/usage/templates/#mandrill-templates) for examples of both.

**Comment by kevgathuku** [comment]
Thanks. Using `global_merge_vars` fixed it.
