### ISSUE TITLE
Use single requests session for each Django email backend connection

### ISSUE THREAD

**Issue by medmunds** [brack3t/Djrill#94]
Right now, Djrill fires up a new request for each outgoing message, creating a new http connection. This is inefficient when sending many messages.

We should create a single requests.Session for each backend instance (each get_connection), and then use that session for all outgoing messages on the Django email backend connection.

(See http://stackoverflow.com/q/30982717/647002)

**Comment by Wrhector** [comment]
I've implemented this feature and PR created: #98

**Comment by medmunds** [comment]
Implemented in v2.0 by #98
