### ISSUE TITLE
Global Mandrill Attributes

### ISSUE THREAD

**Issue by Wrhector** [brack3t/Djrill#97]
What are people's views on allowing mandrill specific mail settings (text2html, track_opens, etc) to be set in the settings file?

My reasoning is that I use my mandrill account for many sites with subacocunts but default settings on the mandrill site are across all subaccounts and would be cleaner than passing attributes every time I call send_mail.

**Comment by Wrhector** [comment]
I've implemented this feature and PR created: #99

**Comment by medmunds** [comment]
My initial reaction was, can't a lot of this be set up in Mandrill's own defaults? But I went and looked, and the Mandrill settings are really pretty limited. So now my reaction is, great idea!

**Comment by Wrhector** [comment]
#99 has been merged
